name: python_3_gpss
channels:
  - defaults
dependencies:
  - jupyter=1.0.0
  - matplotlib=3.1.0
  - nose=1.3.7
  - numpy=1.16.4
  - scipy=1.3.0
  - six=1.12.0
  - pip=19.1.1
  - pip:
    - gpy==1.9.8
    - gpyopt==1.2.5
    - paramz==0.9.5
    - "git+https://github.com/SheffieldML/PyDeepGP"
    - "git+https://github.com/BRML/climin"
